= Projektauftrag Work Manager
 // Metadata
:author: Daniel Andricic, Robert Rajkovaca, Yimne Raid
:date: yyyy-mm-dd
:revision: 1.0
//Settings
:source-highlighter: coderay
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
:imagesdir: images
:sourcedir-code: WorkManager/main/java/at/htl/workmanager
//:sourcedir-test: WorkManager/test/java/at/htl/workmanager
:toc:

Version: {revision}

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++

## Projektbezeichnung
Work Manager

## Projektauftraggeber
Prof. Mag. Dr. Thomas Stütz

## Projekthintergrund
Damit für den Arbeitgeber und Arbeitnehmer die flexible Zeitgestaltung übersichtlicher geplant werden kann, möchten wir eine App/Website für beide
erstellen, die einen Wochenplan oder einen Monatsplan besitzt.
In diesem Plan wird dargestellt wann der Mitarbeiter arbeiten soll.
Der Arbeitgeber kann seinen Plan flexibel aufstellen und bei jeder Änderung soll der betreffende Mitarbeiter sofort benachrichtigt werden.

## Projektergebnis
Das Ergebnis soll eine App/Website sein, die den Arbeitgeber die Arbeitszeiten aller Arbeitnehmer bearbeiten lässt.
Nach jeden Monat wird für jeden Mitarbeiter eine Bilanz seiner/ihrer Arbeitstunden erstellt, so kann Arbeitnehmer und Arbeitgeber sehen, wann, wie lange und wo wurde gearbeitet.

## Projektziele
* Flexible Arbeitszeiten ermöglichen.
* Arbeitnehmer und -geber die Planung erleichtern.
* Eine ähnliche Form von der üblichen Gleitzeit erstellen.


## Projektbeschreibung
Die App soll zuverlässig den Mitarbeiter benachrichtigen, falls sich seine Arbeitszeiten ändern.
Es soll auch nur der betroffene Mitarbeiter benachrichtigt werden.
Arbeitgeber soll so eine bessere Übersicht der Arbeitspläne haben und leichter sicherstellen, dass die Arbeit auch ordentlich ausgeführt wird.
Es sollen keine persönliche Daten an unbefugten Personen weitergeleitet werden.

## Meilensteine
* Webserver einrichten .
* Datenbank-Server einrichten.
* Die ersten Funktionen der App/Website austesten.

## Freigaben
* 20.05.2019 Datenbank-Server eingerichtet
* 20.06.2019 App eingerichtet

## Projektstart

14.10.19

## Projektende

10.07.2020

## Projektressourcen

* Datenbank-Server
* Applikation