= Projektantrag Work Manager
 // Metadata
:author: Daniel Andricic, Robert Rajkovaca, Yimne Raid
:date: yyyy-mm-dd
:revision: 1.0
//Settings
:source-highlighter: coderay
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
:imagesdir: images
:sourcedir-code: WorkManager/main/java/at/htl/workmanager
//:sourcedir-test: WorkManager/test/java/at/htl/workmanager
:toc:

Version: {revision}

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++

=== Projektauftraggeber

Prof. Mag. Dr. Thomas Stütz

=== Projekthintergrund

Damit für den Arbeitgeber und Arbeitnehmer die flexible Zeitgestaltung übersichtlicher geplant werden kann, möchten wir eine App/Website für beide
erstellen, die einen Wochenplan oder einen Monatsplan besitzt.
In diesem Plan wird dargestellt wann der Mitarbeiter arbeiten soll.
Der Arbeitgeber kann seinen Plan flexibel aufstellen und bei jeder Änderung soll der betreffende Mitarbeiter sofort benachrichtigt werden.

=== Projektziele
===== Sinn/Zweck des Projekt

* Eine flexible Zeitgestaltung in Firmen ermöglichen.
* Der Mitarbeiter kann sich mit seinen Boss leichter auf Arbeitszeiten einigen.
* Der Arbeitgeber kann seine Öffnungszeiten flexibler gestalten.
* Der Arbeitgeber kann leichter auf die Ausführung der Tätigkeiten achten.

=== **Funktionen der App**
* Den Arbeitgeber die Arbeitszeiten verschiedener Mitarbeiter flexibel gestalten.
* Den betreffenden Mitarbeiter sofort auf eine Änderung hinweisen.
* Monatsbilanz für die Arbeitstunden erstellen.

=== Betroffene
* Arbeitgeber
* Arbeitnehmer

=== Endergebnis
Das Ergebnis soll eine App/Website sein, die den Arbeitgeber die Arbeitszeiten aller Arbeitnehmer bearbeiten lässt.
Nach jeden Monat wird für jeden Mitarbeiter eine Bilanz seiner/ihrer Arbeitstunden erstellt, so kann Arbeitnehmer und Arbeitgeber sehen, wann, wie lange und wo wurde gearbeitet.

== Projektstart

14.10.2019

== Projektende

01.07.2020

== Projektressourcen
* Datenbank-Server
* Webserver

== Projektrisiken
Risiken:

* Die nicht Vollendigung des Projekts
* Kompatibilitätsrisiken
* Zeitmangel
* Umsetzung des Projekts

== Projektorganisation

Projektmanager: Yimne Raid
Projektteam: Yimne Raid, Daniel Andricic, Robert Rajkovaca
